spring:
  profiles:
    # 默认激活 dev 环境
    active: dev

jwt:
  # 签发人
  issuer: jacob
  # 秘钥
  secret: NERkDDe5fAUotbAORlGao8YD5EnLbNg1C6njbTGHHrfEk6HzPl6l8+eKKOgeUwH4FUB1x/OrAY1Pa+4S82s5Zg==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer